project_id = "fdlyaasqywmdinyaivmw"

[auth]
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[functions.delete-account]
verify_jwt = true

[functions.delete-blocked-account]
verify_jwt = true

[functions.stock-analysis]
verify_jwt = true

[functions.check-email-availability]
verify_jwt = false

[functions.business-tools-advisor]
verify_jwt = true

[functions.sync-credits]
verify_jwt = true

[functions.freemius-webhook]
verify_jwt = false

[functions.ads-advisor]
verify_jwt = true