project_id = "fdlyaasqywmdinyaivmw"

[functions.delete-account]
verify_jwt = true

[functions.send-bulk-notification]
verify_jwt = true

[functions.stock-analysis]
verify_jwt = true

[functions.check-email-availability]
verify_jwt = false

[functions.business-ideas-advisor]
verify_jwt = true

[functions.business-tools-advisor]
verify_jwt = true

[functions.sync-credits]
verify_jwt = true